

/* Create Tables */

CREATE TABLE COMMUNITY_COMMENTS
(
	CC_NO number NOT NULL,
	CC_COMMENT nvarchar2(200) NOT NULL,
	CC_POSTDATE date DEFAULT SYSDATE,
	CM_NO number NOT NULL,
	ID varchar2(50) NOT NULL,
	SM_EMAIL varchar2(50) NOT NULL,
	PRIMARY KEY (CC_NO)
);


CREATE TABLE COMMUNITY_MEMO
(
	CM_NO number NOT NULL,
	CM_TITLE nvarchar2(50) NOT NULL,
	CM_CONTENT nvarchar2(2000) NOT NULL,
	CM_POSTDATE date DEFAULT SYSDATE,
	ID varchar2(50) NOT NULL,
	SM_EMAIL varchar2(50) NOT NULL,
	PRIMARY KEY (CM_NO)
);


CREATE TABLE HEALTHISSUE
(
	H_NAME nvarchar2(50) NOT NULL,
	H_NUTRIENT nvarchar2(200) NOT NULL,
	H_DESC nvarchar2(500) NOT NULL,
	PRIMARY KEY (H_NAME)
);


CREATE TABLE H_RELATED_I
(
	H_NAME nvarchar2(50) NOT NULL,
	I_NAME nvarchar2(50) NOT NULL,
	UNIQUE (H_NAME, I_NAME)
);


CREATE TABLE H_RELATED_N
(
	H_NAME nvarchar2(50) NOT NULL,
	N_NAME nvarchar2(50) NOT NULL,
	UNIQUE (H_NAME, N_NAME)
);


CREATE TABLE INGREDIENT
(
	I_NAME nvarchar2(50) NOT NULL,
	I_DRI nvarchar2(50),
	I_UL nvarchar2(50),
	I_FUNC nvarchar2(200),
	I_DESC nvarchar2(1000),
	I_CAUTION nvarchar2(1000),
	PRIMARY KEY (I_NAME)
);


CREATE TABLE MEMBER
(
	ID varchar2(50) NOT NULL,
	PWD varchar2(50) NOT NULL,
	NAME nvarchar2(50) NOT NULL,
	BIRTH date NOT NULL,
	GENDER nvarchar2(10) NOT NULL,
	EMAIL varchar2(50) NOT NULL,
	SOCIAL nvarchar2(10) NOT NULL,
	REGIDATE date DEFAULT SYSDATE,
	ACTIVE nvarchar2(10) NOT NULL,
	INACTIVE_DATE date,
	SM_EMAIL varchar2(50) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE NOTICEBOARD_COMMENTS
(
	NC_NO number NOT NULL,
	NC_COMMENT nvarchar2(200) NOT NULL,
	NC_POSTDATE date DEFAULT SYSDATE,
	NM_NO number NOT NULL,
	ID varchar2(50) NOT NULL,
	SM_EMAIL varchar2(50) NOT NULL,
	PRIMARY KEY (NC_NO)
);


CREATE TABLE NOTICEBOARD_MEMO
(
	NM_NO number NOT NULL,
	NM_TITLE nvarchar2(50) NOT NULL,
	NM_CONTENT nvarchar2(2000) NOT NULL,
	NM_POSTDATE date DEFAULT SYSDATE,
	ID varchar2(50) NOT NULL,
	SM_EMAIL varchar2(50) NOT NULL,
	PRIMARY KEY (NM_NO)
);


CREATE TABLE NUTRIENT
(
	N_NAME nvarchar2(50) NOT NULL,
	N_DRI_M nvarchar2(50),
	N_UL_M nvarchar2(50),
	N_DRI_F nvarchar2(50),
	N_UL_F nvarchar2(50),
	N_FUNC nvarchar2(200),
	N_DESC nvarchar2(1000),
	N_CAUTION nvarchar2(1000),
	N_LACK nvarchar2(500),
	N_FOOD nvarchar2(500),
	PRIMARY KEY (N_NAME)
);


CREATE TABLE PROFILE_IMAGE
(
	PI_NO number NOT NULL,
	PI_PATH nvarchar2(500) NOT NULL,
	PI_FILENAME nvarchar2(500) NOT NULL,
	PI_EXT nvarchar2(50) NOT NULL,
	ID varchar2(50),
	SM_EMAIL varchar2(50),
	PRIMARY KEY (PI_NO)
);


CREATE TABLE QNA_COMMENTS
(
	QC_NO number NOT NULL,
	QC_COMMENT nvarchar2(200) NOT NULL,
	QC_POSTDATE date DEFAULT SYSDATE,
	QM_NO number NOT NULL,
	ID varchar2(50) NOT NULL,
	SM_EMAIL varchar2(50) NOT NULL,
	PRIMARY KEY (QC_NO)
);


CREATE TABLE QNA_MEMO
(
	QM_NO number NOT NULL,
	QM_TITLE nvarchar2(50) NOT NULL,
	QM_CONTENT nvarchar2(2000) NOT NULL,
	QM_POSTDATE date DEFAULT SYSDATE,
	ID varchar2(50) NOT NULL,
	SM_EMAIL varchar2(50) NOT NULL,
	PRIMARY KEY (QM_NO)
);


CREATE TABLE SELECT_HEALTHISSUE
(
	SH_NO number NOT NULL,
	H_NAME nvarchar2(50) NOT NULL,
	ID varchar2(50),
	SM_EMAIL varchar2(50),
	SH_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (SH_NO),
	UNIQUE (ID, H_NAME)
);


CREATE TABLE SELECT_SUPPLEMENT
(
	SS_NO number NOT NULL,
	S_NAME nvarchar2(100) NOT NULL,
	ID varchar2(50),
	SM_EMAIL varchar2(50),
	SS_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (SS_NO),
	UNIQUE (ID, S_NAME)
);


CREATE TABLE SOCIAL_MEMBER
(
	SM_EMAIL varchar2(50) NOT NULL,
	SM_GENDER nvarchar2(10),
	SM_SITE nvarchar2(50) NOT NULL,
	SM_UPDATE nvarchar2(10),
	SM_NAME nvarchar2(50),
	SM_BIRTH date,
	SM_REGIDATE date DEFAULT SYSDATE,
	PRIMARY KEY (SM_EMAIL)
);


CREATE TABLE SUPPLEMENT
(
	S_NAME nvarchar2(100) NOT NULL,
	S_COMPANY nvarchar2(100),
	S_NUM nvarchar2(100),
	S_REGIDATE nvarchar2(100),
	S_EXPDATE nvarchar2(100),
	S_FORM nvarchar2(100),
	S_DOSE nvarchar2(100),
	S_PACK nvarchar2(100),
	S_STORAGE nvarchar2(2000),
	S_CAUTION nvarchar2(2000),
	S_EFFECT nvarchar2(2000),
	S_STANDARD nvarchar2(2000),
	PRIMARY KEY (S_NAME)
);


CREATE TABLE S_RELATED_I
(
	S_NAME nvarchar2(100) NOT NULL,
	I_NAME nvarchar2(50) NOT NULL,
	UNIQUE (S_NAME, I_NAME)
);


CREATE TABLE S_RELATED_N
(
	S_NAME nvarchar2(100) NOT NULL,
	N_NAME nvarchar2(50) NOT NULL,
	UNIQUE (S_NAME, N_NAME)
);



